#!/bin/bash

TARGET_DIR=$WORKSPACE_DIR/target
if [ $? -eq 0 ]; then
  copy-to-output $TARGET_DIR/*.bin
  log-size $TARGET_DIR/workspace.elf

  # Normalize firmware binary name
  mv $OUTPUT_DIR/workspace.bin $OUTPUT_DIR/firmware.bin
fi
