#!/bin/bash

# Download fimware to cache dir
mkdir -p "$CACHE_DIR/$FIRMWARE_HASH"
clone-repo $FIRMWARE_REPO $FIRMWARE_PATH

# Preprocess .ino files
# preprocess-ino $WORKSPACE_DIR

mkdir -p $WORKSPACE_DIR/target
touch $WORKSPACE_DIR/target/workspace.bin
