#!/bin/bash

CMAKE_VERSION="3.13.0"
CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh"

set -evx

if [ -z "$CIRCLE_TAG" ]; then
	export ARTIFACT_TAG=$(echo "$CIRCLE_BRANCH" | tr '[:upper:]' '[:lower:]' | sed 's,/,-,g')-$(git rev-parse --short HEAD)
else
	export ARTIFACT_TAG=$CIRCLE_TAG
fi

DOCKER_TAG="${ARTIFACT_TAG}-manifest"

docker build -t $DOCKER_IMAGE_NAME --build-arg CMAKE_URL="$CMAKE_URL" .

if [ ! -z "$ARTIFACT_TAG" ]; then
	docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$DOCKER_TAG
	docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
fi

# Push latest
if [ ! -z "$CIRCLE_TAG" ]; then
	docker push $DOCKER_IMAGE_NAME
fi
