#!/bin/bash

GIT_BRANCH="ch39834/workbench-installer"
echo "Pulling manifest from 'device-os' branch '${GIT_BRANCH}'..."

# -e  Abort script at first error, when a command exits with
#     non-zero status.
# -x  Print a trace of simple commands and their arguments
#     after they are expanded and before they are executed.
set -ex

# Generate build image
echo "Generating build environment image '${DOCKER_IMAGE_NAME}'..."
docker build \
	--build-arg GIT_BRANCH="${GIT_BRANCH}" \
	--build-arg GITHUB_TOKEN="${GITHUB_TOKEN}" \
	--build-arg NPM_TOKEN="${NPM_TOKEN}" \
	--tag ${DOCKER_IMAGE_NAME} \
	.

# Only push images if a tag has been specified
if [ ! -z "${TRAVIS_TAG}" ]; then
	# Add tag information
	docker tag ${DOCKER_IMAGE_NAME}:latest ${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}

	# Push all tags
	docker push ${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}
	docker push ${DOCKER_IMAGE_NAME}
fi
